AWSTemplateFormatVersion: 2010-09-09
Description: Emmanuel Ibikunle / Udacity - This template Create an EC2 instance in a given VPC
Parameters:
  myVPC:
    Description: Describes the VPC to use.
    Type: AWS::EC2::VPC::Id
  sshKeyName:
    Description: Key to be used to ssh into the server
    Type: String
  publicSubnetId:
    Description: Public subnet id
    Type: AWS::EC2::Subnet::Id
  AMItoUse:
    Description: AMI to use for our base image
    Type: String

Resources:
  WebserverSecurityGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Creates a Security Group which only allows inbound access on TCP port 80 and also allows unrestricted outbound access
      VpcId:
        Ref: myVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
  WebserverInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId:
        Ref: AMItoUse
      KeyName:
        Ref: sshKeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - Ref: "WebserverSecurityGrp"
          SubnetId:
            Ref: publicSubnetId
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y httpd
          sudo systemctl start httpd
          sudo systemctl enable httpd

# aws cloudformation create-stack --stack-name mySecGrpWithEC2WPStack --region us-east-1 --template-body file://sample/challenge1-with-parameters.yaml --parameters file://sample/challenge1-params.json
# aws cloudformation delete-stack --stack-name mySecGrpWithEC2WPStack --region us-east-1
