AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  myUsername:
    Description: Any username
    Type: String
  myPassword:
    Description: A password with at least 8 characters
    Type: String

Reources:
  # Database Resouce
  myDBSubnetGroup1:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: "Subnets to use for the DB"
      DBSubnetGroupName: "Subnet Group For DB"
      # Replace these IDs, as applicable to you
      SubnetIds:
        - subnet-045e261987a91fa63
        - subnet-056e13b0a88c48a92

  # Choose a name of your choice
  MyDB:
    Type: "AWS::RDS::DBInstance"
    Properties:
      VPCSecurityGroups: [sg-id-comes-here]
      PibliclyAccessible: false
      MultiAZ: false
      AllocationStorage: 20
      DBinstanceClass: db.t2.small
      Engine: "mysql"
      MasterUsername: !Sub "${myUsername}"
      MasterPaswword: !Sub "${myPassword}"
      DBSubnetGroupName: !Ref myDBSubnetGroup11
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName} MS SQL RDS"
    # DeletionPolicy: "Retain"
# aws cloudformation create-stack  --stack-name RDSstack --region us-east-1 --template-body file://sample/exercise-db.yaml --parameters file://sample/exercise-db.json --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM"
# https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/put-bucket-policy.html#examples
